% Mooring Design and Dynamics Package
% This package can assist in the design and evaluation of oceanographic moorings.
% It has been tested on MATLAB 5.2 under Windows (95 and NT) and HP-UNIX.
% Written be R.K.Dewey Version 1.04 5/98 (rdewey@uvic.ca)
%
% moordesign.m         Main program to design and test a mooring
% moordyn.m            Main mooring dynamics code
% modmoor.m            Menu to modify mooring elements
% loadmd.m             Menu to load previously saved mooring
% savemd.m             Menu to save a mooring
% getvelocity.m        Menu to input/load velocity profiles
% getwirel.m           Menu to input wire/chain length
% mdplot.m             Routine to plot mooring in 3D forced by sheared currents
% addelement.m         Menu to add and element to an existing mooring
% dismoor.m            Display the mooring elements, buoyancies, heights,...
% makemovie.m          Makes a movie of mooring positions is velocity is a timeseries
% savemovie.m          Saves a movie, or timeseries generated by makemovie.m
% plot_elements.m	   Plots the vertical mooring (not to scale) with real components
% pltchain.m           Plots chian sections
% pltwire.m            Plots wire sections
% pltanchor.m          Plots an anchor
% pltcm.m              Plots a current meter (even Aanderaas)
% pltfloat.m           Plots a float
% pltmisc.m            Plots a miscellaneous component as a cylinder
% pltrelease.m         Plots an acoustic release
%
% mmposition.mat       Mat file containing the main menu relative window position
% mdcodes.mat          Mat file containing mooring element information
% moor001.mat          An example (simple) mooring
% moor001ts.mat        A time dependant version of moor001
% moor002.mat          An example surface "S" mooring
% moor002ts.mat        A time dependant version of moor002
% CDMDUM1.mat          An example mooring from CDMS Users Manual
% vel001.mat           Example velocity profiles
% addelehelp.mat       Help file available for adding/deleting elements
% velhelp.mat          Help file available for inputing velocity profiles
%
% moordyn.html         HTML documentation describing dynamics solution
% texture.bmp          HTML background texture
% mdeq01.gif           Equation gifs needed by "moordyn.html"
% mdeq02.gif           "
% mdeq03.gif           "
% mdeq04.gif           "
%