function getvelocity(command)
% Enter/Load the velocity profile(s)
global U V W z rho vel dep den time uw vw
global Ht Bt Cdt MEt moorelet Usp Vsp DD % for a Towed Body
global h_edit_velocity h_edit_depths h_edit_density h_edit_windspd h_edit_winddir h_edit_shipsp
global windspd winddir Usp Vsp uvsp
global fs

if nargin==0, command=0; end
if command<40 & (uw^2+vw^2)==0,
   windspd=0;winddir=360;
   uw=windspd*0.02*cos((90-winddir+180)*pi/180);
   vw=windspd*0.02*sin((90-winddir+180)*pi/180);
elseif command<40 & (uw^2+vw^2)>0,
   windspd=sqrt(uw^2+vw^2)/0.02;
   winddir=90-(atan2(vw,uw)*180/pi)+180;
   winddir=mod(winddir,360);
end
if ~isempty(Usp),
   uvsp=num2str([Usp Vsp]);
end
if isempty(DD), DD=0; end
if command == 0,
   figure(4);clf
   set(gcf,'Units', 'Normalized',...
      'Position',[.05 .02 .4 .3],...
      'Name','Load Environmental Conditions',...
      'Color',[.8 .8 .8],...
      'tag','getvelocity');
   h_push_entervel=uicontrol('Style','pushbutton',...
      'Callback','getvelocity(2)',...
      'String','Enter/Edit Velocities Manually','FontSize',fs,...
      'Units','normalized',...
      'Position',[.2 .85 .6 .1]);
   if ~isempty(U) & ~isempty(z),
     h_push_loadvel=uicontrol('Style','pushbutton',...
      'Callback','getvelocity(1)',...
      'String','Load Velocity File','FontSize',fs,...
      'Units','normalized',...
      'Position',[.05 .7 .4 .1]);
     h_push_savevel=uicontrol('Style','pushbutton',...
      'Callback','getvelocity(11)',...
      'String','Save Velocity File','FontSize',fs,...
      'Units','normalized',...
      'Position',[.55 .7 .4 .1]);
   else
     h_push_loadvel=uicontrol('Style','pushbutton',...
      'Callback','getvelocity(1)',...
      'String','Load Velocity File','FontSize',fs,...
      'Units','normalized',...
      'Position',[.25 .7 .5 .1]);
   end
   h_push_enterden=uicontrol('Style','pushbutton',...
      'Callback','getvelocity(22)',...
      'String','Enter/Edit Densities Manually','FontSize',fs,...
      'Units','normalized',...
      'Position',[.2 .55 .6 .1]);
   if ~isempty(rho),
     h_push_loadden=uicontrol('Style','pushbutton',...
      'Callback','getvelocity(21)',...
      'String','Load Density File','FontSize',fs,...
      'Units','normalized',...
      'Position',[.05 .4 .4 .1]);
     h_push_saveden=uicontrol('Style','pushbutton',...
      'Callback','getvelocity(31)',...
      'String','Save Density File','FontSize',fs,...
      'Units','normalized',...
      'Position',[.55 .4 .4 .1]);
   else
     h_push_loadden=uicontrol('Style','pushbutton',...
      'Callback','getvelocity(21)',...
      'String','Load Density File','FontSize',fs,...
      'Units','normalized',...
      'Position',[.25 .4 .5 .1]);
   end
   h_push_loadwinds=uicontrol('Style','pushbutton',...
      'Callback','getvelocity(41)',...
      'String','Enter Winds','FontSize',fs,...
      'Units','normalized',...
      'Position',[.05 .25 .4 .1]);
   h_push_entershipsp=uicontrol('Style','pushbutton',...
      'Callback','getvelocity(44)',...
      'String','Enter Ship Speed','FontSize',fs,...
      'Units','normalized',...
      'Position',[.55 .25 .4 .1]);
   h_help=uicontrol('Style','Pushbutton',...
      'String','Help','FontSize',fs,...
      'Units','normalized',...
      'Position',[.15 .03 .2 .125],...
      'Callback','getvelocity(12)');
   h_close=uicontrol('Style','Pushbutton',...
      'String','Close','FontSize',fs,...
      'Units','normalized',...
      'Position',[.65 .03 .2 .125],...
      'Callback','getvelocity(50)');
   h_edit_velocity=[];
   h_edit_depths=[];
   if isempty(vel) | isempty(dep),
      vel='0 0 0';
      dep='120 10 0';
   end
   if isempty(den),
      den='1024 1025 1026';
   end
   if isempty(uvsp),
      uvsp='0 0';
   end  
   if isempty(U), U=str2num(vel); V=0.0*ones(size(U)); W=V; end
   if isempty(z), z=str2num(dep); end
   if isempty(rho), rho=str2num(den); end
end
if command == 1,
   [ifile,ipath]=uigetfile('*.mat','Load Existing Velocity File');
   if ifile~=0,
      load([ipath ifile]);
   end
   clear ifile ipath
elseif command == 21,
   [ifile,ipath]=uigetfile('*.mat','Load Existing Density File');
   if ifile~=0,
      load([ipath ifile]);
   end
   clear ifile ipath
elseif command == 2,
      figure(4);clf;
         h_push_uvel=uicontrol('Style','pushbutton',...
           'Callback','getvelocity(3)',...
           'String','Enter U Velocities','FontSize',fs,...
           'Units','normalized',...
           'Position',[.2 .85 .6 .1]);
         h_push_uvel=uicontrol('Style','pushbutton',...
           'Callback','getvelocity(5)',...
           'String','Enter Z Depths','FontSize',fs,...
           'Units','normalized',...
           'Position',[.2 .7 .6 .1]);
         h_push_vvel=uicontrol('Style','pushbutton',...
           'Callback','getvelocity(7)',...
           'String','Enter V Velocities','FontSize',fs,...
           'Units','normalized',...
           'Position',[.2 .55 .6 .1]);
         h_push_wvel=uicontrol('Style','pushbutton',...
           'Callback','getvelocity(9)',...
           'String','Enter W Velocities','FontSize',fs,...
           'Units','normalized',...
           'Position',[.2 .4 .6 .1]);
         h_push_uvwsave=uicontrol('Style','pushbutton',...
           'Callback','getvelocity(11)',...
           'String','Save Velocities','FontSize',fs,...
           'Units','normalized',...
           'Position',[.2 .25 .6 .1]);
         h_help=uicontrol('Style','Pushbutton',...
           'String','Help','FontSize',fs,...
           'Units','normalized',...
           'Position',[.15 .03 .2 .1],...
           'Callback','getvelocity(12)');
        h_close=uicontrol('Style','Pushbutton',...
           'String','Close','FontSize',fs,...
           'Units','normalized',...
           'Position',[.65 .03 .2 .1],...
           'Callback','getvelocity(0)');
elseif command == 22,
      figure(4);clf;
         h_push_den=uicontrol('Style','pushbutton',...
           'Callback','getvelocity(23)',...
           'String','Enter Densities','FontSize',fs,...
           'Units','normalized',...
           'Position',[.2 .75 .6 .2]);
         h_push_zden=uicontrol('Style','pushbutton',...
           'Callback','getvelocity(5)',...
           'String','Enter Z Depths','FontSize',fs,...
           'Units','normalized',...
           'Position',[.2 .45 .6 .2]);
         h_push_densave=uicontrol('Style','pushbutton',...
           'Callback','getvelocity(31)',...
           'String','Save Density Profile','FontSize',fs,...
           'Units','normalized',...
           'Position',[.2 .25 .6 .15]);
         h_help=uicontrol('Style','Pushbutton',...
           'String','Help','FontSize',fs,...
           'Units','normalized',...
           'Position',[.15 .03 .2 .1],...
           'Callback','getvelocity(12)');
         h_close=uicontrol('Style','Pushbutton',...
           'String','Close','FontSize',fs,...
           'Units','normalized',...
           'Position',[.65 .03 .2 .1],...
           'Callback','getvelocity(0)');
elseif command == 3,
   clf;
   if ~isempty(U),
      [mu,nu]=size(U);
      if mu==length(z),
         vel=num2str(U(:,1)');
      else
         vel=num2str(U(1,:));
      end
   end
   h_text_velocity=uicontrol('Style','text',...
      'String','Enter U Velocities [m/s]','FontSize',fs,...
      'Units','normalized',...
      'Position',[.05 .7 .3 .2]);
   h_edit_velocity=uicontrol('Style','edit',...
      'Callback','getvelocity(4)',...
      'String',vel,'FontSize',fs,...
      'Units','Normalized',...
      'Position',[.4 .7 .5 .2]);
   h_ok=uicontrol('Style','Pushbutton',...
      'String','OK','FontSize',fs,...
      'Units','normalized',...
      'Position',[.4 .25 .2 .2],...
      'Callback','getvelocity(4)');
   h_help=uicontrol('Style','Pushbutton',...
      'String','Help','FontSize',fs,...
      'Units','normalized',...
      'Position',[.15 .03 .2 .15],...
      'Callback','getvelocity(12)');
   h_close=uicontrol('Style','Pushbutton',...
      'String','Close','FontSize',fs,...
      'Units','normalized',...
      'Position',[.65 .03 .2 .15],...
      'Callback','getvelocity(50)');
elseif command == 23,
   clf;
   if ~isempty(rho),
      [md,nd]=size(rho);
      if md==length(z),
         den=num2str(rho(:,1)');
      else
         den=num2str(rho(1,:));
      end
   end
   h_text_density=uicontrol('Style','text',...
      'String','Enter Densities [kg/m^3]','FontSize',fs,...
      'Units','normalized',...
      'Position',[.05 .7 .3 .2]);
   h_edit_density=uicontrol('Style','edit',...
      'Callback','getvelocity(24)',...
      'String',den,'FontSize',fs,...
      'Units','Normalized',...
      'Position',[.4 .7 .5 .2]);
   h_ok=uicontrol('Style','Pushbutton',...
      'String','OK','FontSize',fs,...
      'Units','normalized',...
      'Position',[.4 .25 .2 .2],...
      'Callback','getvelocity(24)');
   h_help=uicontrol('Style','Pushbutton',...
      'String','Help','FontSize',fs,...
      'Units','normalized',...
      'Position',[.15 .03 .2 .15],...
      'Callback','getvelocity(12)');
   h_close=uicontrol('Style','Pushbutton',...
      'String','Close','FontSize',fs,...
      'Units','normalized',...
      'Position',[.65 .03 .2 .15],...
      'Callback','getvelocity(50)');
elseif command == 4,
   U=str2num(get(h_edit_velocity,'String'));
   U=U(:);
   if length(V)~=length(U), V=zeros(size(U)); end
   if length(W)~=length(U), W=zeros(size(U)); end
   getvelocity(5);
elseif command == 24,
   den=get(h_edit_density,'String');
   rho=str2num(den);
   getvelocity(22);
elseif command == 5,
   clf;
   if ~isempty(z),
      [mz,nz]=size(z);
      if mz==length(z),
         dep=num2str(z');
      else
         dep=num2str(z);
      end
   end
   h_text_depths=uicontrol('Style','text',...
     'String','Enter Heights [m]','FontSize',fs,...
     'Units','normalized',...
     'Position',[.05 .7 .3 .2]);
   h_edit_depths=uicontrol('Style','edit',...
     'Callback','getvelocity(6)',...
     'String',dep,'FontSize',fs,...
     'Units','Normalized',...
     'Position',[.4 .7 .5 .2]);
   h_ok=uicontrol('Style','Pushbutton',...
      'String','OK','FontSize',fs,...
      'Units','normalized',...
      'Position',[.4 .25 .2 .2],...
      'Callback','getvelocity(6)');
   h_help=uicontrol('Style','Pushbutton',...
      'String','Help','FontSize',fs,...
      'Units','normalized',...
      'Position',[.15 .03 .2 .15],...
      'Callback','getvelocity(12)');
   h_close=uicontrol('Style','Pushbutton',...
      'String','Close','FontSize',fs,...
      'Units','normalized',...
      'Position',[.65 .03 .2 .15],...
      'Callback','getvelocity(50)');
elseif command == 6,
   z=str2num(get(h_edit_depths,'String'));
   if z(length(z)) == 0 | z(1) == 0,
      getvelocity(0);
   else
      msgbox(' Velocity profile must have value at the bottom (z=0) ');
      figure(4);
      getvelocity(0); 
   end
elseif command == 7,
   clf;
   if ~isempty(V), 
      [mv,nv]=size(V);
      if mv==length(z),
         vel=num2str(V(:,1)');
      else
         vel=num2str(V(1,:));
      end
   end
   if length(V) ~= length(U), V=zeros(size(U)); vel=num2str(V); end
   h_text_velocity=uicontrol('Style','text',...
      'String','Enter V Velocities [m/s]','FontSize',fs,...
      'Units','normalized',...
      'Position',[.05 .7 .3 .2]);
   h_edit_velocity=uicontrol('Style','edit',...
      'Callback','getvelocity(8)',...
      'String',vel,'FontSize',fs,...
      'Units','Normalized',...
      'Position',[.4 .7 .5 .2]);
   h_ok=uicontrol('Style','Pushbutton',...
      'String','OK','FontSize',fs,...
      'Units','normalized',...
      'Position',[.4 .25 .2 .2],...
      'Callback','getvelocity(8)');
   h_help=uicontrol('Style','Pushbutton',...
      'String','Help','FontSize',fs,...
      'Units','normalized',...
      'Position',[.15 .03 .2 .15],...
      'Callback','getvelocity(12)');
   h_close=uicontrol('Style','Pushbutton',...
      'String','Close','FontSize',fs,...
      'Units','normalized',...
      'Position',[.65 .03 .2 .15],...
      'Callback','getvelocity(50)');
elseif command == 8,
   V=str2num(get(h_edit_velocity,'String'));
   V=V(:);
   getvelocity(2);
elseif command == 9,
   clf;
   if ~isempty(W), 
      [mw,nw]=size(W);
      if mw==length(W), W=W'; end
      vel=num2str(W); 
   end
   if length(W) ~= length(U), W=zeros(size(U)); vel=num2str(W); end
   h_text_velocity=uicontrol('Style','text',...
      'String','Enter W Velocities [m/s]','FontSize',fs,...
      'Units','normalized',...
      'Position',[.05 .7 .3 .2]);
   h_edit_velocity=uicontrol('Style','edit',...
      'Callback','getvelocity(10)',...
      'String',vel,'FontSize',fs,...
      'Units','Normalized',...
      'Position',[.4 .7 .5 .2]);
   h_ok=uicontrol('Style','Pushbutton',...
      'String','OK','FontSize',fs,...
      'Units','normalized',...
      'Position',[.4 .25 .2 .2],...
      'Callback','getvelocity(10)');
   h_help=uicontrol('Style','Pushbutton',...
      'String','Help','FontSize',fs,...
      'Units','normalized',...
      'Position',[.15 .03 .2 .15],...
      'Callback','getvelocity(12)');
   h_close=uicontrol('Style','Pushbutton',...
      'String','Close','FontSize',fs,...
      'Units','normalized',...
      'Position',[.65 .03 .2 .15],...
      'Callback','getvelocity(50)');
elseif command == 10,
   W=str2num(get(h_edit_velocity,'String'));
   getvelocity(2);
elseif command == 11,
   [ofile,opath]=uiputfile('*.mat','Save Velocities File');
   if ~isempty(ofile) & ~isempty(opath), save([opath,ofile],'U','V','W','z');end
   clear ofile opath
   getvelocity(0);
elseif command == 31,
   [ofile,opath]=uiputfile('*.mat','Save Density File');
   if ~isempty(ofile) & ~isempty(opath), save([opath,ofile],'den','z');end
   clear ofile opath
   getvelocity(0);
elseif command == 12,
   load velhelp.mat
   h_velhelp=msgbox(velhelp);
   hpos=get(h_velhelp,'Position');
   set(h_velhelp,'Position',[hpos(1) 10 hpos(3) hpos(4)]);
   clear velhelp
elseif command==40,
   if isempty(vel) | isempty(dep),
      vel='0 0 0';
      dep='120 10 0';
   end
   if length(time)>1, % then we've loaded a time series
      Udis=U(:,1);
      Vdis=V(:,1);
      Wdis=W(:,1);
      if size(rho)==size(U),
         rhodis=rho(:,1);
      else
         rhodis=rho;
      end
   else
      Udis=U;Vdis=V;Wdis=W;rhodis=rho;
   end
   %
% Add 2% of wind speed to top current value(s)
    if uw~=0 | vw ~=0,
    windepth=sqrt(uw^2+vw^2)/0.02; % wind penetrates about 1m for every 1m/s, otherwise shears too high
    if (uw^2+vw^2)>0, % we actually have a wind
    if windepth > z(1), windepth==0.8*z(1); end % maximum wind depth is 80% of water depth
    if z(2)<(z(1)-windepth),  % add a new velocity at depth with no wind effect
      mu=length(z);
      zdis(3:mu+1)=zdis(2:mu);
      zdis(2)=zdis(1)-windepth;
      Udis(3:mu+1)=Udis(2:mu);
      Udis(2)=interp1([z(1) z(3)],[Udis(1) Udis(3)],z(2),'linear');
      Udis(1)=Udis(1)+uw;
      Vdis(3:mu+1)=Vdis(2:mu);
      Vdis(2)=interp1([z(1) z(3)],[Vdis(1) Vdis(3)],z(2),'linear');
      Vdis(1)=Vdis(1)+vw;
      Wdis(3:mu+1)=Wdis(2:mu);
      Wdis(2)=interp1([z(1) z(3)],[Wdis(1) Wdis(3)],z(2),'linear');
      rhodis(3:mu+1)=rhodis(2:mu);
      rhodis(2)=rhodis(1);
   else % this is affecting more than one velocity value
      uwindx=find(z > (z(1)-windepth));
      uw1=interp1([z(1) z(1)-windepth],[uw 0],z(uwindx),'linear');
      vw1=interp1([z(1) z(1)-windepth],[vw 0],z(uwindx),'linear');
      izero=find(abs(uw1)<0.01);uw1(izero)=0;
      izero=find(abs(uw1)<0.01);uw1(izero)=0;
      qq=0;
      for wi=uwindx,
          qq=qq+1;
          Udis(wi)=Udis(wi)+uw1(qq);
          Vdis(wi)=Vdis(wi)+vw1(qq);
      end
   end
   end
   end
%
   %
   if isempty(Udis), Udis=str2num(vel); end
   if isempty(Vdis), Vdis=zeros(size(Udis)); end
   if isempty(Wdis), Wdis=zeros(size(Udis)); end
   if isempty(z), z=str2num(dep); end
   if isempty(rhodis), rhodis=1025*ones(size(Udis));end;
   if isempty(moorelet),
   	disp(' Height[m]    U [m/s]    V [m/s]    W [m/s] Density [kg/m^3]');
      %     123456789112345678921234567893123456789412345678951234567896
   else
   	disp(' Depth [m]    U [m/s]    V [m/s]    W [m/s] Density [kg/m^3]');
      %     123456789112345678921234567893123456789412345678951234567896
   end
      
   zdis=z;
   %
   for i=1:length(zdis),
      if zdis(i)>999.99,
         disp([' ',num2str([zdis(i) Udis(i) Vdis(i) Wdis(i) rhodis(i)],'%11.2f')]);
      elseif zdis(i)<1000 & zdis(i)>99.99,
         disp(['  ',num2str([zdis(i) Udis(i) Vdis(i) Wdis(i) rhodis(i)],'%11.2f')]);
      elseif zdis(i)<100 & zdis(i)>9.99,
         disp(['   ',num2str([zdis(i) Udis(i) Vdis(i) Wdis(i) rhodis(i)],'%11.2f')]);
      elseif zdis(i)<10,
         disp(['    ',num2str([zdis(i) Udis(i) Vdis(i) Wdis(i) rhodis(i)],'%11.2f')]);
      end
   end
   if ~isempty(Usp),
      disp(' ');
      disp(' Ship U [m/s]   Ship V [m/s]');
      %     123456789112345678921234567893123456789
      disp(['    ',num2str([Usp Vsp],'%11.2f')]);      
   end
      
elseif command==41,
   clf;
   h_text_winds1=uicontrol('Style','text',...
      'String','Enter Wind Speed [m/s]','FontSize',fs,...
      'Units','normalized',...
      'Position',[.05 .8 .4 .15]);
   h_edit_windspd=uicontrol('Style','edit',...
      'Callback','getvelocity(42)',...
      'String',windspd,'FontSize',fs,...
      'Units','Normalized',...
      'Position',[.6 .8 .3 .15]);
   h_text_winds2=uicontrol('Style','text',...
      'String','Enter Wind Direction','FontSize',fs,...
      'Units','normalized',...
      'Position',[.05 .6 .4 .1]);
   h_text_winds21=uicontrol('Style','text',...
      'String','Met Style: In compass degrees for the direction the wind is coming FROM',...
      'Units','normalized','FontSize',fs,...
      'Position',[.05 .35 .4 .25]);
   h_edit_winddir=uicontrol('Style','edit',...
      'Callback','getvelocity(42)',...
      'String',winddir,'FontSize',fs,...
      'Units','Normalized',...
      'Position',[.6 .55 .3 .15]);
   h_ok=uicontrol('Style','Pushbutton',...
      'String','OK','FontSize',fs,...
      'Units','normalized',...
      'Position',[.4 .2 .2 .15],...
      'Callback','getvelocity(42)');
   h_help=uicontrol('Style','Pushbutton',...
      'String','Help','FontSize',fs,...
      'Units','normalized',...
      'Position',[.15 .03 .2 .15],...
      'Callback','getvelocity(12)');
   h_close=uicontrol('Style','Pushbutton',...
      'String','Close','FontSize',fs,...
      'Units','normalized',...
      'Position',[.65 .03 .2 .15],...
      'Callback','getvelocity(0)');
elseif command == 42, % add about 2%of wind speed to current (no Ekman Spiral)
   windspd=str2num(get(h_edit_windspd,'String'));
   winddir=str2num(get(h_edit_winddir,'String'));
   uw=windspd*0.02*cos((90-winddir+180)*pi/180);
   vw=windspd*0.02*sin((90-winddir+180)*pi/180);
   getvelocity(41);
elseif command==44,
   clf;
   h_text_shipsp1=uicontrol('Style','text',...
      'String','Enter Ship Velocities [m/s]','FontSize',fs,...
      'Units','normalized',...
      'Position',[.05 .6 .5 .15]);
   h_edit_shipsp=uicontrol('Style','edit',...
      'Callback','getvelocity(45)',...
      'String',uvsp,'FontSize',fs,...
      'Units','Normalized',...
      'Position',[.65 .6 .3 .15]);
   h_close=uicontrol('Style','Pushbutton',...
      'String','Close','FontSize',fs,...
      'Units','normalized',...
      'Position',[.4 .1 .2 .15],...
      'Callback','getvelocity(52)');
elseif command == 45,
   uvsp=str2num(get(h_edit_shipsp,'String'));
   Usp=uvsp(1);
   Vsp=uvsp(2);
   getvelocity(44);
elseif command==47,
   figure(4);clf
   set(gcf,'Units', 'Normalized',...
      'Position',[.05 .02 .3 .2],...
      'Name','Set Desired Depth of Towed Body',...
      'Color',[.8 .8 .8],...
      'tag','getvelocity');
   h_text_shipsp1=uicontrol('Style','text',...
      'String','Enter Desired Depth [m]','FontSize',fs,...
      'Units','normalized',...
      'Position',[.05 .6 .5 .25]);
   h_edit_shipsp=uicontrol('Style','edit',...
      'Callback','getvelocity(48)',...
      'String',DD,'FontSize',fs,...
      'Units','Normalized',...
      'Position',[.65 .6 .3 .25]);
   h_close=uicontrol('Style','Pushbutton',...
      'String','Close','FontSize',fs,...
      'Units','normalized',...
      'Position',[.4 .1 .2 .25],...
      'Callback','getvelocity(51)');
elseif command == 48,
   DD=str2num(get(h_edit_shipsp,'String'));
   getvelocity(47);
elseif command==50,
   uw=windspd*0.02*cos((90-winddir+180)*pi/180);
   vw=windspd*0.02*sin((90-winddir+180)*pi/180);
elseif command==51,
   DD=str2num(get(h_edit_shipsp,'String'));
elseif command==52,
   uvsp=str2num(get(h_edit_shipsp,'String'));
   Usp=uvsp(1);
   Vsp=uvsp(2);
end
%
if command>=50 & command <=52,
   % clean up vectors
	[mu,nu]=size(U);
	if mu==1 | nu==1,
	   U=U(:);V=V(:);W=W(:);
	   if length(rho)~=length(U),
	      [pp,ss]=polyfit([max(z) min(z)],[min(rho) max(rho)],1); % recall z is height
	      rho=polyval(pp,z);
	      rho=rho(:);
	   end
	end
	if min(z) ~= 0 & length(time)<2,
	   z(length(z)+1)=0;
	   U(length(U)+1)=0;
	   V(length(V)+1)=0;
	   W(length(W)+1)=0;
	   rho(length(rho)+1)=max(rho)+0.01;
	end
   % display things then leave
   if length(time)>1, % then we've loaded a time series
      Udis=U(:,1);
      Vdis=V(:,1);
      Wdis=W(:,1);
      zdis=z(:,1);
      if size(rho)==size(U),
         rhodis=rho(:,1);
      else
         rhodis=rho;
      end
   else
      Udis=U;Vdis=V;Wdis=W;zdis=z;rhodis=rho;
   end
   %
   if isempty(Udis), Udis=str2num(vel); end
   if isempty(Vdis), Vdis=zeros(size(Udis)); end
   if isempty(Wdis), Wdis=zeros(size(Udis)); end
   if isempty(zdis), zdis=str2num(dep); end
   if isempty(rhodis), rhodis=1025*ones(size(Udis));end;
   if isempty(moorelet),
   	disp(' Height[m]    U [m/s]    V [m/s]    W [m/s] Density [kg/m^3]');
      %     123456789112345678921234567893123456789412345678951234567896
   else
   	disp(' Depth [m]    U [m/s]    V [m/s]    W [m/s] Density [kg/m^3]');
      %     123456789112345678921234567893123456789412345678951234567896
   end
% Add 2% of wind speed to top current value(s)
    if uw~=0 | vw ~=0,
    windepth=sqrt(uw^2+vw^2)/0.02; % wind penetrates about 1m for every 1m/s, otherwise shears too high
    if (uw^2+vw^2)>0, % we actually have a wind
    if windepth > z(1), windepth==0.8*z(1); end % maximum wind depth is 80% of water depth
    if z(2)<(z(1)-windepth),  % add a new velocity at depth with no wind effect
      mu=length(z);
      z(3:mu+1)=z(2:mu);
      z(2)=z(1)-windepth;
      Udis(3:mu+1)=Udis(2:mu);
      Udis(2)=interp1([z(1) z(3)],[Udis(1) Udis(3)],z(2),'linear');
      Udis(1)=Udis(1)+uw;
      Vdis(3:mu+1)=Vdis(2:mu);
      Vdis(2)=interp1([z(1) z(3)],[Vdis(1) Vdis(3)],z(2),'linear');
      Vdis(1)=Vdis(1)+vw;
      Wdis(3:mu+1)=Wdis(2:mu);
      Wdis(2)=interp1([z(1) z(3)],[Wdis(1) Wdis(3)],z(2),'linear');
      rhodis(3:mu+1)=rhodis(2:mu);
      rhodis(2)=rhodis(1);
   else % this is affecting more than one velocity value
      uwindx=find(z > (z(1)-windepth));
      uw1=interp1([z(1) z(1)-windepth],[uw 0],z(uwindx),'linear');
      vw1=interp1([z(1) z(1)-windepth],[vw 0],z(uwindx),'linear');
      izero=find(abs(uw1)<0.01);uw1(izero)=0;
      izero=find(abs(uw1)<0.01);uw1(izero)=0;
      qq=0;
      for wi=uwindx,
          qq=qq+1;
          Udis(wi)=Udis(wi)+uw1(qq);
          Vdis(wi)=Vdis(wi)+vw1(qq);
      end
   end
   end
   end
%
   for i=1:length(zdis),
      if zdis(i)>999.99,
         disp([' ',num2str([zdis(i) Udis(i) Vdis(i) Wdis(i) rhodis(i)],'%11.2f')]);
      elseif zdis(i)<1000 & zdis(i)>99.99,
         disp(['  ',num2str([zdis(i) Udis(i) Vdis(i) Wdis(i) rhodis(i)],'%11.2f')]);
      elseif zdis(i)<100 & zdis(i)>9.99,
         disp(['   ',num2str([zdis(i) Udis(i) Vdis(i) Wdis(i) rhodis(i)],'%11.2f')]);
      elseif zdis(i)<10,
         disp(['    ',num2str([zdis(i) Udis(i) Vdis(i) Wdis(i) rhodis(i)],'%11.2f')]);
      end
   end
   if ~isempty(Usp),
      disp(' ');
      disp(' Ship U [m/s]   Ship V [m/s]');
      %     123456789112345678921234567893123456789
      disp(['    ',num2str([Usp Vsp],'%11.2f')]);      
   end
   close(4);
   moordesign(0);
end

% fini
